import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-full`}>
        <div id="root" className="flex flex-col min-h-screen">
          <nav className="p-4 rounded-b-2xl bg-primary">
            <div>I am a Machine Learning Engineer</div>
            <div className="flex flex-row-reverse">
              <a className="p-2 inline-block mt-4 px-6 py-2 bg-yellow-500 text-white font-semibold rounded hover:bg-yellow-600 transition-colors" href="/"  target="_blank"
              rel="noopener noreferrer">home</a>
              <a className="p-2 inline-block mt-4 px-6 py-2 bg-yellow-500 text-white font-semibold rounded hover:bg-yellow-600 transition-colors" target="_blank"
              rel="noopener noreferrer" href="/projects">projects</a>
              <a className="p-2 inline-block mt-4 px-6 py-2 bg-yellow-500 text-white font-semibold rounded hover:bg-yellow-600 transition-colors" target="_blank"
              rel="noopener noreferrer" href="/blog">blog</a>
            </div>
          </nav>
          <main className="flex-grow">{children}</main>
          <footer className="p-8 bg-fuchsia-200 flex justify-center items-center space-x-4">
            <a
              href="https://github.com/Sumanthraju4104"
              className="inline-block mt-4 px-6 py-2 bg-yellow-500 text-white font-semibold rounded hover:bg-yellow-600 transition-colors"
              target="_blank"
              rel="noopener noreferrer"
              
            >
              Github
            </a>
            <a
              href="https://linkedin.com/in/sumanth-raju-36b278280"
              className="inline-block mt-4 px-6 py-2 bg-yellow-500 text-white font-semibold rounded hover:bg-yellow-600 transition-colors"
              target="_blank"
              rel="noopener noreferrer"
            >
              LinkedIn
            </a>
          </footer>
        </div>
      </body>
    </html>
  );
}
